timestamps: false
behaviors:
  softDelete: false
  auditTrail: false
  immutable: false
  assignable: false
  orderable: true
access:
  scope: owner
  permissions:
    create: authenticated
    read: owner
    update: owner
    delete: owner
  sharing: false
views:
  default:
    defaultView: list
    enabledViews:
      - list
  table:
    design: minimal
    pageSize: 20
  card:
    size: default
    orientation: grid
    imageStyle: none
  list:
    density: comfortable
  detail:
    display: page
  pagination:
    table:
      mode: offset
      pageSize: 20
    list:
      mode: infinite
    card:
      mode: infinite
    cover:
      mode: infinite
operations:
  create: true
  read: true
  update: true
  delete: true
search: false
searchFields:
  - title
  - description
i18n:
  languages:
    - en
    - es
name: todos
label: Todo
labelPlural: Todos
fields:
  title:
    type: string
    required: true
    max: 200
    showOn: all
    hideOn: &a1 []
    filterable: false
    sortable: true
  completed:
    type: boolean
    required: false
    max: 200
    showOn: all
    hideOn: *a1
    filterable: true
    sortable: true
    default: false
indexes:
  - name: by_userId
    fields:
      - userId
  - name: by_completed
    fields:
      - completed
