/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutRouteImport } from './routes/_app/login/_layout'
import { Route as AppDevMailboxRouteImport } from './routes/_app/dev/mailbox'
import { Route as AppLoginLayoutIndexRouteImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthOnboardingLayoutRouteImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardLayoutRouteImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameRouteImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutTeamPoolRouteImport } from './routes/_app/_auth/dashboard/_layout.team-pool'
import { Route as AppAuthDashboardLayoutTasksRouteImport } from './routes/_app/_auth/dashboard/_layout.tasks'
import { Route as AppAuthDashboardLayoutTicketsRouteImport } from './routes/_app/_auth/dashboard/_layout.tickets'
import { Route as AppAuthDashboardLayoutTodosRouteImport } from './routes/_app/_auth/dashboard/_layout.todos'
import { Route as AppAuthDashboardLayoutSettingsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutSettingsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthDashboardLayoutProjectsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.projects.index'
import { Route as AppAuthDashboardLayoutProjectsProjectIdRouteImport } from './routes/_app/_auth/dashboard/_layout.projects.$projectId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutRoute = AppLoginLayoutRouteImport.update({
  id: '/login/_layout',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppDevMailboxRoute = AppDevMailboxRouteImport.update({
  id: '/dev/mailbox',
  path: '/dev/mailbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutIndexRoute = AppLoginLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)
const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)
const AppAuthDashboardLayoutTeamPoolRoute =
  AppAuthDashboardLayoutTeamPoolRouteImport.update({
    id: '/team-pool',
    path: '/team-pool',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutTasksRoute =
  AppAuthDashboardLayoutTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutTicketsRoute =
  AppAuthDashboardLayoutTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutTodosRoute =
  AppAuthDashboardLayoutTodosRouteImport.update({
    id: '/todos',
    path: '/todos',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutProjectsIndexRoute =
  AppAuthDashboardLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutProjectsProjectIdRoute =
  AppAuthDashboardLayoutProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/mailbox': typeof AppDevMailboxRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/dashboard/tasks': typeof AppAuthDashboardLayoutTasksRoute
  '/dashboard/tickets': typeof AppAuthDashboardLayoutTicketsRoute
  '/dashboard/todos': typeof AppAuthDashboardLayoutTodosRoute
  '/dashboard/team-pool': typeof AppAuthDashboardLayoutTeamPoolRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/projects/$projectId': typeof AppAuthDashboardLayoutProjectsProjectIdRoute
  '/dashboard/projects/': typeof AppAuthDashboardLayoutProjectsIndexRoute
  '/dashboard/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/mailbox': typeof AppDevMailboxRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login': typeof AppLoginLayoutIndexRoute
  '/dashboard/tasks': typeof AppAuthDashboardLayoutTasksRoute
  '/dashboard/tickets': typeof AppAuthDashboardLayoutTicketsRoute
  '/dashboard/todos': typeof AppAuthDashboardLayoutTodosRoute
  '/dashboard/team-pool': typeof AppAuthDashboardLayoutTeamPoolRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/projects/$projectId': typeof AppAuthDashboardLayoutProjectsProjectIdRoute
  '/dashboard/projects': typeof AppAuthDashboardLayoutProjectsIndexRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/dev/mailbox': typeof AppDevMailboxRoute
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/dashboard/_layout/tasks': typeof AppAuthDashboardLayoutTasksRoute
  '/_app/_auth/dashboard/_layout/tickets': typeof AppAuthDashboardLayoutTicketsRoute
  '/_app/_auth/dashboard/_layout/todos': typeof AppAuthDashboardLayoutTodosRoute
  '/_app/_auth/dashboard/_layout/team-pool': typeof AppAuthDashboardLayoutTeamPoolRoute
  '/_app/_auth/onboarding/_layout/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/projects/$projectId': typeof AppAuthDashboardLayoutProjectsProjectIdRoute
  '/_app/_auth/dashboard/_layout/projects/': typeof AppAuthDashboardLayoutProjectsIndexRoute
  '/_app/_auth/dashboard/_layout/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev/mailbox'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/login/'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/tickets'
    | '/dashboard/todos'
    | '/dashboard/team-pool'
    | '/onboarding/username'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev/mailbox'
    | '/onboarding'
    | '/login'
    | '/dashboard/tasks'
    | '/dashboard/tickets'
    | '/dashboard/todos'
    | '/dashboard/team-pool'
    | '/onboarding/username'
    | '/dashboard'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/dev/mailbox'
    | '/_app/login/_layout'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/dashboard/_layout/tasks'
    | '/_app/_auth/dashboard/_layout/tickets'
    | '/_app/_auth/dashboard/_layout/todos'
    | '/_app/_auth/dashboard/_layout/team-pool'
    | '/_app/_auth/onboarding/_layout/username'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/dashboard/_layout/projects/$projectId'
    | '/_app/_auth/dashboard/_layout/projects/'
    | '/_app/_auth/dashboard/_layout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev/mailbox': {
      id: '/_app/dev/mailbox'
      path: '/dev/mailbox'
      fullPath: '/dev/mailbox'
      preLoaderRoute: typeof AppDevMailboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexRouteImport
      parentRoute: typeof AppLoginLayoutRoute
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameRouteImport
      parentRoute: typeof AppAuthOnboardingLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/team-pool': {
      id: '/_app/_auth/dashboard/_layout/team-pool'
      path: '/team-pool'
      fullPath: '/dashboard/team-pool'
      preLoaderRoute: typeof AppAuthDashboardLayoutTeamPoolRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/tasks': {
      id: '/_app/_auth/dashboard/_layout/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof AppAuthDashboardLayoutTasksRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/tickets': {
      id: '/_app/_auth/dashboard/_layout/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof AppAuthDashboardLayoutTicketsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/todos': {
      id: '/_app/_auth/dashboard/_layout/todos'
      path: '/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof AppAuthDashboardLayoutTodosRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/projects/': {
      id: '/_app/_auth/dashboard/_layout/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof AppAuthDashboardLayoutProjectsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/projects/$projectId': {
      id: '/_app/_auth/dashboard/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof AppAuthDashboardLayoutProjectsProjectIdRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
  }
}

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsIndexRoute: typeof AppAuthDashboardLayoutSettingsIndexRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsIndexRoute:
      AppAuthDashboardLayoutSettingsIndexRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutTasksRoute: typeof AppAuthDashboardLayoutTasksRoute
  AppAuthDashboardLayoutTicketsRoute: typeof AppAuthDashboardLayoutTicketsRoute
  AppAuthDashboardLayoutTodosRoute: typeof AppAuthDashboardLayoutTodosRoute
  AppAuthDashboardLayoutTeamPoolRoute: typeof AppAuthDashboardLayoutTeamPoolRoute
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
  AppAuthDashboardLayoutProjectsProjectIdRoute: typeof AppAuthDashboardLayoutProjectsProjectIdRoute
  AppAuthDashboardLayoutProjectsIndexRoute: typeof AppAuthDashboardLayoutProjectsIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutTasksRoute: AppAuthDashboardLayoutTasksRoute,
    AppAuthDashboardLayoutTicketsRoute: AppAuthDashboardLayoutTicketsRoute,
    AppAuthDashboardLayoutTodosRoute: AppAuthDashboardLayoutTodosRoute,
    AppAuthDashboardLayoutTeamPoolRoute: AppAuthDashboardLayoutTeamPoolRoute,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
    AppAuthDashboardLayoutProjectsProjectIdRoute:
      AppAuthDashboardLayoutProjectsProjectIdRoute,
    AppAuthDashboardLayoutProjectsIndexRoute:
      AppAuthDashboardLayoutProjectsIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutUsernameRoute: typeof AppAuthOnboardingLayoutUsernameRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutUsernameRoute: AppAuthOnboardingLayoutUsernameRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppDevMailboxRoute: typeof AppDevMailboxRoute
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppDevMailboxRoute: AppDevMailboxRoute,
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
